name: Deploy Spring Boot App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to EC2 using SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 13.221.243.153
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "target/ai-integration-1.0.0.jar"
          target: "/home/ec2-user/proxyAiInegration/"

      - name: Restart Spring Boot App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.221.243.153
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pkill -f 'ai-integration-1.0.0.jar' || true
            nohup java -jar /home/ec2-user/proxyAiInegration/ai-integration-1.0.0.jar > output.log 2>&1 &
